line_length:
  warning: 120
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
disabled_rules: # rule identifiers to exclude from running
  # - colon
  - comma
  # - control_statement
  - variable_name
  - force_cast
  - large_tuple
  - notification_center_detachment
  - nesting
  - function_parameter_count
  - trailing_whitespace 
excluded:
  - BaseApp/AppDelegate.swift